Petstagram/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin

from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Petstagram.common.urls')),
    path('accounts/', include('Petstagram.accounts.urls')),
    path('pets/', include('Petstagram.pets.urls')),
    path('photos/', include('Petstagram.photos.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Petstagram/common/models.py
from django.contrib.auth import get_user_model
from django.db import models

from Petstagram.photos.models import Photo

UserModel = get_user_model()


class Comment(models.Model):
    text = models.TextField(max_length=300, blank=False, null=False)
    date_time_of_publication = models.DateTimeField(auto_now_add=True, null=False, blank=True)
    to_photo = models.ForeignKey(Photo, on_delete=models.CASCADE, null=False, blank=True)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-date_time_of_publication']


class Like(models.Model):
    to_photo = models.ForeignKey(Photo, on_delete=models.CASCADE)
    user = models.ForeignKey(UserModel, on_delete=models.CASCADE)

templates/base/partials/nav.html
{% load static %}
<nav class="navbar">
    <div class="container">
        <div class="logo">
            <!-- Link to Home Page -->
            <a href="{% url 'index' %}">
                <img width="50px" src="{% static 'images/free-30-instagram-stories-icons23_122570.png' %}" alt="img1">
            </a>

            <!-- Link to Home Page -->
            <a class="home" href="{% url 'index' %}">
                <i>Petstagram</i>
            </a>
        </div>

        <div class="nav-links">
            <ul class="nav-group">
                {% if request.user.is_authenticated %}
                    <li class="nav-item">
                        <!-- Link to Add Pet Page -->
                        <a href="{% url 'add pet' %}">
                            <i>Add Pet</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <!-- Link to Add Photo Page -->
                        <a href="{% url 'add photo' %}">
                            <i>Add Photo</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <!-- Link to Profile Page -->
                        <a href="{% url 'details user' pk=request.user.pk %}">
                            <i>Profile</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'logout user' %}">
                            <i>Logout</i>
                        </a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a href="{% url 'register user' %}">
                            <i>Register</i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <a href="{% url 'login user' %}">
                            <i>Log In</i>
                        </a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

templates/base/partials/photo-item.html
{% load static %}
<div class="card">
    <!-- Start User Details and Image Location -->
    <div class="top">
        <div class="userDetails">
            <!-- Link to User Profile Page -->
            <a href="{% url 'details user' pk=photo.user_id %}">
                <div class="profilepic">
                    <div class="profile_img">
                        <div class="image">
                            <img src="{% static 'images/person.png' %}" alt="img8">
                        </div>
                    </div>
                </div>
            </a>
            <h3>
                <!-- Link to User Profile Page -->
                <a href="{% url 'details user' pk=photo.user_id %}">
                    <!-- if user has first name and last name -->
                    {% if photo.user.get_full_name %}
                        {{ photo.user.get_full_name }}
                    {% else %}
                        <!-- show user username -->
                        {{ photo.user.username }}
                    {% endif %}
                </a>
                <br>
                <!-- if the photo has location -->
                {% if photo.location %}
                    <span>{{ photo.location }}</span>
                {% endif %}
            </h3>
        </div>
    </div>
    <!-- End User Details and Image Location -->

    <!-- Start Pet Photo -->
    <div class="imgBx" id="{{ photo.pk }}">
        <img src="/media/{{ photo.photo }}" alt="post" class="cover">
    </div>
    <!-- End Pet Photo -->

    <!-- Start Like and Share Buttons -->
    <div class="bottom">
        <div class="actionBtns">
            <div class="left">
                <!-- Start Like Button -->
                <span class="heart">
                    <a href="{% url 'like' photo.id %}">
                        <!-- if user has liked the photo -->
                        {% if photo.liked_by_user %}
                            <svg style="color: red"
                                 xmlns="http://www.w3.org/2000/svg"
                                 width="24"
                                 height="24"
                                 fill="currentColor"
                                 class="bi bi-heart-fill"
                                 viewBox="0 0 16 16">
                            <!-- Coordinate path -->
                            <path fill-rule="evenodd"
                                  d="M8 1.314C12.438-3.248 23.534 4.735
                                  8 15-7.534 4.736 3.562-3.248 8 1.314z"
                                  fill="red">

                            </path>
                        </svg>
                            <!-- else -->
                        {% else %}
                            <svg aria-label="Like"
                                 color="#262626"
                                 fill="#262626"
                                 height="24"
                                 role="img"
                                 viewBox="0 0 48 48"
                                 width="24">
                        <!-- Coordinate path -->
                        <path d="M34.6 6.1c5.7 0 10.4 5.2 10.4
                                    11.5 0 6.8-5.9 11-11.5 16S25 41.3 24
                                    41.9c-1.1-.7-4.7-4-9.5-8.3-5.7-5-11.5-9.2-11.5-16C3
                                    11.3 7.7 6.1 13.4 6.1c4.2 0 6.5 2 8.1 4.3
                                    1.9 2.6 2.2 3.9 2.5 3.9.3 0 .6-1.3 2.5-3.9
                                    1.6-2.3 3.9-4.3 8.1-4.3m0-3c-4.5 0-7.9
                                    1.8-10.6 5.6-2.7-3.7-6.1-5.5-10.6-5.5C6 3.1
                                    0 9.6 0 17.6c0 7.3 5.4 12 10.6 16.5.6.5 1.3
                                    1.1 1.9 1.7l2.3 2c4.4 3.9 6.6 5.9 7.6 6.5.5.3
                                    1.1.5 1.6.5.6 0 1.1-.2 1.6-.5 1-.6 2.8-2.2
                                    7.8-6.8l2-1.8c.7-.6 1.3-1.2 2-1.7C42.7 29.6
                                    48 25 48 17.6c0-8-6-14.5-13.4-14.5z">
                        </path>
                    </svg>
                        {% endif %}
                    </a>
                </span>
                <!-- End Like Button -->

                <!-- Start Share Button -->
                <a href="{% url 'share' photo.id %}">
                    <svg aria-label="Share Post" class="_8-yf5 " color="#262626" fill="#262626"
                         height="24" role="img" viewBox="0 0 48 48" width="24">
                        <path d="M47.8 3.8c-.3-.5-.8-.8-1.3-.8h-45C.9 3.1.3
										3.5.1 4S0 5.2.4 5.7l15.9 15.6 5.5 22.6c.1.6.6
										1 1.2 1.1h.2c.5 0 1-.3
										1.3-.7l23.2-39c.4-.4.4-1 .1-1.5zM5.2
										6.1h35.5L18 18.7 5.2 6.1zm18.7
										33.6l-4.4-18.4L42.4 8.6 23.9 39.7z">
                        </path>
                    </svg>
                </a>
                <!-- End Share Button -->

            </div>
        </div>
        <!-- End Like and Share Buttons -->

        <!-- Number of Likes per Photo -->
        <p class="likes">{{ photo.like_set.count }} likes</p>


        <!-- Start Tagged Pets -->
        {% for pet in photo.tagged_pets.all %}
            <a href="{% url 'details pet' username=photo.user.username slug=pet.slug %}">
                <p class="message">
                    <b>{{ pet.name }}</b>
                </p>
            </a>
        {% endfor %}
        <!-- End Tagged Pets -->

        <!-- Link to Photo Details Page -->
        <a href="{% url 'details photo' pk=photo.pk %}">
            <h4 class="details">See details</h4>
        </a>

        <!-- Date of Publication -->
        <h5 class="postTime">{{ photo.publication_date }}</h5>

        <!-- Start Add Comments Section -->
        <div class="addComments">
            <div class="reaction">
                <h3>
                    <i class="far fa-smile"></i>
                </h3>
            </div>
            <!-- Start Add Comments Form -->
            {#            <form method="post" action="#">#}
            {#                <label for="id_body">Body:</label>#}
            {#                <textarea name="body" cols="40" rows="10" placeholder="Add comment..." maxlength="300"#}
            {#                          required="" id="id_body"></textarea>#}
            {#                <button type="submit">Post</button>#}
            {#            </form>#}
            <form action="{% url 'add comment' photo_id=photo.pk %}" method="post">
                {{ comment_form }}
                <button type="submit">Submit</button>
                {% csrf_token %}
            </form>
            <!-- End Add Comments Form -->

        </div>
        <!-- End Add Comments Section -->

    </div>
</div>